

class AlreadyRunningException(Exception):
    pass


class NotRunningException(Exception):
    pass
